package com.waveapp.tarotai.presentation.manualload

import androidx.compose.foundation.BorderStroke
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.ArrowBack
import androidx.compose.material.icons.filled.Add
import androidx.compose.material.icons.filled.Check
import androidx.compose.material.icons.filled.Close
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.unit.dp
import androidx.hilt.navigation.compose.hiltViewModel
import com.waveapp.tarotai.domain.model.CardOrientation
import com.waveapp.tarotai.domain.model.ManualLoadCard

/**
 * Pantalla de carga manual de tirada.
 *
 * Permite al usuario cargar una tirada física carta por carta, seleccionando:
 * - Qué carta está en cada posición
 * - La orientación de cada carta (derecha/invertida)
 *
 * Layout:
 * - Header con info de la tirada y progreso
 * - Grid/Lista de posiciones con placeholders
 * - Botón "Generar Interpretación" (habilitado cuando está completa)
 *
 * Navegación:
 * - Click en posición vacía → CardSelectorScreen
 * - Click en posición llena → Dialog para cambiar/remover
 * - Interpretación completa → InterpretationScreen
 *
 * @param onNavigateBack Callback para volver atrás
 * @param onNavigateToCardSelector Callback para ir al selector de cartas (positionIndex)
 * @param onNavigateToInterpretation Callback cuando se genera interpretación exitosamente
 * @param viewModel ViewModel inyectado por Hilt
 *
 * @since v1.1.0
 */
@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun ManualLoadScreen(
    onNavigateBack: () -> Unit,
    onNavigateToCardSelector: (Int) -> Unit,
    onNavigateToInterpretation: () -> Unit,
    viewModel: ManualLoadViewModel = hiltViewModel()
) {
    val configuration by viewModel.configuration.collectAsState()
    val isLoading by viewModel.isLoading.collectAsState()
    val error by viewModel.error.collectAsState()
    val interpretationGenerated by viewModel.interpretationGenerated.collectAsState()

    // Navegar a interpretación cuando se genera
    LaunchedEffect(interpretationGenerated) {
        if (interpretationGenerated != null) {
            onNavigateToInterpretation()
            viewModel.clearInterpretationGenerated()
        }
    }

    // Mostrar error en Snackbar
    val snackbarHostState = remember { SnackbarHostState() }
    LaunchedEffect(error) {
        error?.let {
            snackbarHostState.showSnackbar(it)
            viewModel.clearError()
        }
    }

    Scaffold(
        topBar = {
            TopAppBar(
                title = { Text("Cargar Tirada Manual") },
                navigationIcon = {
                    IconButton(onClick = onNavigateBack) {
                        Icon(
                            imageVector = Icons.AutoMirrored.Filled.ArrowBack,
                            contentDescription = "Volver"
                        )
                    }
                }
            )
        },
        snackbarHost = { SnackbarHost(snackbarHostState) }
    ) { paddingValues ->
        Column(
            modifier = Modifier
                .fillMaxSize()
                .padding(paddingValues)
                .verticalScroll(rememberScrollState())
                .padding(16.dp)
        ) {
            // Header con info y progreso
            ManualLoadHeader(
                consultantName = configuration.consultantName,
                spreadTypeName = getSpreadTypeName(configuration.spreadType.name),
                question = configuration.question,
                progress = configuration.getProgress()
            )

            Spacer(modifier = Modifier.height(24.dp))

            // Posiciones de cartas
            Text(
                text = "Posiciones",
                style = MaterialTheme.typography.titleMedium,
                fontWeight = FontWeight.Bold
            )

            Spacer(modifier = Modifier.height(12.dp))

            configuration.spreadType.positions.forEachIndexed { index, positionName ->
                val cardAtPosition = configuration.getCardAtPosition(index)

                CardPositionItem(
                    positionName = positionName,
                    positionIndex = index,
                    card = cardAtPosition,
                    onCardClick = { onNavigateToCardSelector(index) },
                    onRemoveCard = { viewModel.removeCard(index) }
                )

                Spacer(modifier = Modifier.height(8.dp))
            }

            Spacer(modifier = Modifier.height(24.dp))

            // Botón de generar interpretación
            Button(
                onClick = { viewModel.generateInterpretation() },
                modifier = Modifier.fillMaxWidth(),
                enabled = configuration.isComplete() && !isLoading
            ) {
                if (isLoading) {
                    CircularProgressIndicator(
                        modifier = Modifier.size(20.dp),
                        color = MaterialTheme.colorScheme.onPrimary
                    )
                    Spacer(modifier = Modifier.width(8.dp))
                    Text("Generando interpretación...")
                } else {
                    Icon(
                        imageVector = Icons.Default.Check,
                        contentDescription = null
                    )
                    Spacer(modifier = Modifier.width(8.dp))
                    Text("Generar Interpretación")
                }
            }

            // Texto de ayuda
            if (!configuration.isComplete()) {
                Spacer(modifier = Modifier.height(8.dp))
                val (current, required) = configuration.getProgress()
                Text(
                    text = "Selecciona las $required cartas para continuar ($current/$required)",
                    style = MaterialTheme.typography.bodySmall,
                    color = MaterialTheme.colorScheme.onSurfaceVariant,
                    textAlign = TextAlign.Center,
                    modifier = Modifier.fillMaxWidth()
                )
            }
        }
    }
}

@Composable
private fun ManualLoadHeader(
    consultantName: String,
    spreadTypeName: String,
    question: String?,
    progress: Pair<Int, Int>
) {
    Card(
        modifier = Modifier.fillMaxWidth(),
        colors = CardDefaults.cardColors(
            containerColor = MaterialTheme.colorScheme.primaryContainer
        )
    ) {
        Column(modifier = Modifier.padding(16.dp)) {
            Text(
                text = consultantName,
                style = MaterialTheme.typography.headlineSmall,
                fontWeight = FontWeight.Bold
            )
            Spacer(modifier = Modifier.height(4.dp))
            Text(
                text = spreadTypeName,
                style = MaterialTheme.typography.bodyMedium,
                color = MaterialTheme.colorScheme.primary
            )

            if (!question.isNullOrBlank()) {
                Spacer(modifier = Modifier.height(8.dp))
                Text(
                    text = "\"$question\"",
                    style = MaterialTheme.typography.bodyMedium,
                    fontWeight = FontWeight.Medium
                )
            }

            Spacer(modifier = Modifier.height(12.dp))

            // Progreso
            val (current, required) = progress
            LinearProgressIndicator(
                progress = { current.toFloat() / required.toFloat() },
                modifier = Modifier.fillMaxWidth(),
            )
            Spacer(modifier = Modifier.height(4.dp))
            Text(
                text = "Progreso: $current de $required cartas",
                style = MaterialTheme.typography.bodySmall
            )
        }
    }
}

@Composable
private fun CardPositionItem(
    positionName: String,
    positionIndex: Int,
    card: ManualLoadCard?,
    onCardClick: () -> Unit,
    onRemoveCard: () -> Unit
) {
    Card(
        modifier = Modifier
            .fillMaxWidth()
            .clickable(onClick = onCardClick),
        border = if (card == null) {
            BorderStroke(2.dp, MaterialTheme.colorScheme.outline.copy(alpha = 0.5f))
        } else null
    ) {
        Row(
            modifier = Modifier
                .padding(16.dp)
                .fillMaxWidth(),
            horizontalArrangement = Arrangement.SpaceBetween,
            verticalAlignment = Alignment.CenterVertically
        ) {
            Column(modifier = Modifier.weight(1f)) {
                Text(
                    text = positionName,
                    style = MaterialTheme.typography.bodyLarge,
                    fontWeight = FontWeight.Medium
                )

                if (card != null) {
                    Spacer(modifier = Modifier.height(4.dp))
                    Text(
                        text = card.card.name,
                        style = MaterialTheme.typography.bodyMedium,
                        color = MaterialTheme.colorScheme.primary
                    )
                    Text(
                        text = if (card.orientation == CardOrientation.UPRIGHT) "Derecha" else "Invertida",
                        style = MaterialTheme.typography.bodySmall,
                        color = if (card.orientation == CardOrientation.UPRIGHT)
                            MaterialTheme.colorScheme.primary
                        else
                            MaterialTheme.colorScheme.error
                    )
                } else {
                    Spacer(modifier = Modifier.height(4.dp))
                    Text(
                        text = "Toca para seleccionar carta",
                        style = MaterialTheme.typography.bodySmall,
                        color = MaterialTheme.colorScheme.onSurfaceVariant
                    )
                }
            }

            if (card != null) {
                IconButton(onClick = onRemoveCard) {
                    Icon(
                        imageVector = Icons.Default.Close,
                        contentDescription = "Remover carta",
                        tint = MaterialTheme.colorScheme.error
                    )
                }
            } else {
                Icon(
                    imageVector = Icons.Default.Add,
                    contentDescription = "Agregar carta",
                    tint = MaterialTheme.colorScheme.primary
                )
            }
        }
    }
}

private fun getSpreadTypeName(spreadType: String): String {
    return when (spreadType) {
        "YES_NO" -> "Tirada Sí o No"
        "PRESENT" -> "Tirada de 3 Cartas (Presente)"
        "TENDENCY" -> "Tirada de 3 Cartas (Tendencia)"
        "CROSS" -> "Cruz Celta"
        "SIMPLE" -> "Carta Simple"
        else -> spreadType
    }
}
